<?php
    /**
* Webkul Software.
*
* @category Webkul
* @package Webkul_MarketplaceBaseShipping
* @author Webkul
* @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
* @license https://store.webkul.com/license.html
*/
 ?>
<?php 
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
//$helper = $this->helper('Webkul\MarketplaceBaseShipping\Helper\Data');
$isPartner = $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
?>
<?php 
    if($isPartner){ ?>
        <li class="nav item <?php echo strpos($magentoCurrentUrl,'baseshipping/shipping') !== false ? "current":"";?>">
       <?php 
        if(strpos($magentoCurrentUrl,'baseshipping/shipping') !== false){ ?>      
            <strong><?php echo __('Shipping Setting') ?></strong>              
            <?php
        } else{ ?>        
            <a href="<?php echo $block->getUrl('baseshipping/shipping'); ?>">
                <?php echo __('Shipping Setting') ?>
            </a>                    
        <?php 
            } ?>                  
        </li> 
<?php }?>
