<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MarketplaceBaseShipping
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
 ?>
<?php
    $_helper = $this->helper('Webkul\Marketplace\Helper\Data');
    $isPartner = $_helper->isSeller();
    $isSellerGroup = $_helper->isSellerGroupModuleInstalled();
    $magentoCurrentUrl = $block->getCurrentUrl();
    //$helper = $this->helper('Webkul\MpAramexShipping\Helper\Data');
?>
<?php if ($isPartner): ?>
<?php if (($isSellerGroup && $_helper->isAllowedAction('baseshipping/shipping')) || !$isSellerGroup): ?>
    <li id="wk-mp-menu-base-shipping" class="level-2 <?php echo strpos($magentoCurrentUrl, 'baseshipping/shipping')? "current active":"";?>">
        <a href="<?php echo $block->getUrl('baseshipping/shipping', ['_secure' => $this->getRequest()->isSecure()]); ?>">
            <?php /* @escapeNotVerified */ echo __('Shipping Setting') ?>
        </a>
    </li>
<?php endif; ?>
<?php endif; ?>