<div class="header-container header-style-18">
	<div class="header-middle header-bottom">
		<div class="container">
			<div class="middle-content">
				<div class="row">
					<div class="col-lg-3 col-md-12 logo-header">
						<?php echo $block->getChildHtml('logo_theme'); ?>
					</div>
					
					<div class="col-lg-6 col-md-8 menu-header">
						<div class="menu-container">
							<div class="main-megamenu">
								<?php
									if($_config->getGeneral('menu_style') == 'megamenu'){
										echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
									} else {
										 echo $block->getLayout()->createBlock('Magento\Theme\Block\Html\Topmenu')->setTemplate('Magento_Theme::html/topmenu.phtml')->toHtml(); 
										  
									}
								?>
							</div>
							
							<div class="navigation-mobile-container">
								<?php echo $block->getChildHtml('navigation.mobile'); ?>
							</div>
						</div>
					</div>
					
					<div class="col-lg-3 col-md-4 customer-action">
						<!--<div class="setting-header">
							<div class="custom-icon custom-setting">
								//<?php echo __('Setting')?>//
							</div>
							
							<div class="dropdown-header">
								<p class="title-dropdown"><?php echo __('Language')?></p>
								<?php echo $block->getChildHtml('language-header'); ?>
								<p class="title-dropdown"><?php echo __('Currency')?></p>
								<?php echo $block->getChildHtml('currency-header'); ?>
							</div>
						</div> -->
						
						<div class="customer-header">
							<div class="custom-icon custom-customer">
								<?php echo __('Customer')?>
							</div>
							
							<div class="dropdown-header">
								<p class="title-dropdown"><?php echo __('My Account')?></p>
								<?php echo $block->getChildHtml('toplinks-header'); ?>
							</div>
						</div>
						
						<?php echo $block->getChildHtml('cart-header'); ?>
						
						
						
						<div class="search-header">
							<div class="custom-icon custom-search">
								<?php echo __('Search')?>
							</div>
							
							<?php echo $block->getChildHtml('search-header'); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	/*require([
		'jquery'
	], function ($) {
		$( ".header-style-18 .toplinks-wrapper .header.links li" ).not( ".myaccount-link" ).mouseover(function() {
			$( ".header-style-18 .toplinks-wrapper .header.links" ).addClass('toplinks_hover');
		}).mouseout(function() {
			$( ".header-style-18 .toplinks-wrapper .header.links" ).removeClass('toplinks_hover');
		});
	});*/
</script>