<?php
	$_config = $this->helper('Sm\Market\Helper\Data');
?>
<div class="footer footer-wrapper">
<div class="footer-container footer-style-4">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ft4-block2')->toHtml();?>
	<!--<div class="copyright-payment">
		<div class="container">
			<div class="copyright">
				<?php /*if($_config->getAdvanced('custom_copyright')){ */?>
					<address><?php /*echo $_config->getAdvanced('copyright_content') */?></address>
				<?php /*} else {*/?>
					<address><?php /*echo $block->getCopyright() */?></address>
				<?php /*} */?>
			</div>
		</div>
	</div>-->
</div>
</div>
	

