<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_PurchaseManagement
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div id="sales_order_view_tabs_order_info_content">
	<section class="admin__page-section order-view-account-information">
    	<div class="admin__page-section-content">
       
	        <div class="box-left admin__page-section-item order-information">
	            <!--Order Information-->
	            <div class="entry-edit">
	                <div class="entry-edit-head admin__page-section-item-title">
	                    <span class="icon-head head-account title">Incoming Shipment <?php echo $block->getPickingData()->getIncrementId(); ?></span>
	                </div>
	                <div class="fieldset admin__page-section-item-content">
	                    <table cellspacing="0" class="form-list admin__table-secondary order-information-table">
	                        <tbody>
	                            <tr>
	                                <td class="label"><label>Scheduled Date</label></td>
	                                <td class="value"><strong><?php $date = date_create($block->getPickingData()->getScheduleDate());echo date_format($date, "g:ia \o\\n l jS F Y"); ?></strong></td>
	                            </tr>
	                            <tr>
	                                    <td class="label"><label>Source</label></td>
	                                    <td class="value">
	                            <?php   $source = $block->getPickingData()->getSource();
	                                    $purchase_id = $block->getPickingData()->getPurchaseId();
	                            ?>
	                                        <a target="_blank" href="<?php echo $this->getUrl('purchasemanagement/order/view',array("id"=>$purchase_id));?>"><strong><?php echo $source; ?></strong></a>
	                                    </td>
	                                </tr>
	                            <tr>
	                            <tr>
	                                <td class="label"><label>Picking Status</label></td>
	                                <td class="value"><strong><span>
	<?php                               $status_id = $block->getPickingData()->getStatus();
	                                    if($status_id == 0)
	                                        echo __("New");
	                                    if($status_id == 1)
	                                        echo __("Ready To Receive");
	                                    if($status_id == 2)
	                                        echo __("Received"); 
	                                    if($status_id == 3)
	                                        echo __("Canceled");        ?> 
	                                </span></strong></td>
	                            </tr>
	                        </tbody>
	                    </table>
	                </div>
	            </div>
	        </div>
	        <div class="box-right admin__page-section-item order-account-information">
	            <!--Account Information-->
	            <div class="entry-edit">
	                <div class="entry-edit-head admin__page-section-item-title">
	                    <span class="icon-head head-account title">Supplier Information</span>
	                    <div class="tools"></div>
	                </div>
	                <div class="fieldset admin__page-section-item-content">
	                    <div class="hor-scroll">
	                        <table cellspacing="0" class="form-list admin__table-secondary order-account-information-table">
	                            <tbody>
	                                <tr>
	                                    <td class="label"><label>Supplier Name</label></td>
	                                    <td class="value">
	<?php                                   $supplier_id = $block->getPickingData()->getSupplierId();
	                                        $supplier = $block->getSupplier($supplier_id);   ?>
	                                        <a target="_blank" href="<?php echo $this->getUrl('*/suppliers/edit',array("id"=>$supplier_id));?>"><strong><?php echo $supplier->getName(); ?></strong></a>
	                                    </td>
	                                </tr>
	                                <tr>
	                                    <td class="label"><label>Email</label></td>
	<?php                                    $supplier_email = $supplier->getEmail(); ?>
	                                    <td class="value"><a href="mailto:<?php echo $supplier_email; ?>"><strong><?php echo $supplier_email; ?></strong></a></td>
	                                </tr>
	                            </tbody>
	                        </table>
	                    </div>
	                </div>
	            </div>
	        </div>
	    </div>
	</section>
    <section class="admin__page-section">
        <div class="entry-edit">
            <div class="entry-edit-head admin__page-section-title">
                <span class="icon-head head-products title">Items Ordered</span>
            </div>
        </div>
        <div class="grid np admin__table-wrapper">
            <div class="hor-scroll">
                <table cellspacing="0" class="data order-tables data-table admin__table-primary edit-order-table">
                   
                    <thead>
                        <tr class="headings">
                            <th>Product</th>
                            <th class="a-center">Scheduled Date</th>
                            <th class="a-center width-eighty">Weight</th>
                            <th class="a-center width-eighty">Qty</th>
                            <th class="a-center width-twenty">Status</th>
                        </tr>
                    </thead>
<?php           $count = 1;
                $collection = $block->getMoveObj()->getCollection()->addFieldToFilter("picking_id",$this->getRequest()->getParam("id"));
                foreach ($collection as $order_item) {          ?>
                    <tbody class="<?php if($count % 2 == 0)echo 'even';else echo 'odd';?>">
                        <tr class="border">
                            <td>
                                <div class="item-container">
                                    <div class="item-text">
                                        <h5 class="title">
                                            <span><?php echo $order_item->getDescription(); ?></span>
                                        </h5>
                                        <div><strong>SKU:</strong><?php echo $order_item->getSku(); ?></div>
<?php                                   $option_arr = unserialize($order_item->getCustomOptions());
                                        if($option_arr && isset($option_arr["options"])){  ?>
                                        <dl class="item-options">
<?php                                       foreach($option_arr["options"] as $option) {        ?>
                                                <dt><?php echo $option["label"];?></dt>
                                                <dd><?php echo $option["value"];?></dd>
<?php                                       }       ?>
                                        </dl>
<?php                                   }   ?>
                                    </div>
                                </div>
                            </td>
                            <td class="a-center"><strong><span><?php $date = date_create($order_item->getScheduleDate());echo date_format($date, "g:ia \o\\n l jS F Y"); ?></span></td>
                            <td class="a-center"><strong><span><?php echo $order_item->getWeight();?></span></td>
                            <td>
                                <?php if($block->getPickingData()->getStatus() > 0){?>
                                    <table cellspacing="0" class="qty-table">
                                        <tbody>
                                            <tr>
                                                <td>Ordered</td>
                                                <td><strong><span><?php echo $order_item->getQuantity();?></span></strong></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                <?php }else{?>
                                    <table cellspacing="0" class="qty-table">
                                        <tbody>
                                            <tr>
                                                <td>Ordered</td>
                                                <td><strong><input type="text" name="qty" class="item_qty width-eighty" value="<?php echo $order_item->getQuantity(); ?>"/></strong></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                <?php }?>
                            </td>

                            <td class="a-center">
                                <strong><span>
<?php                               $status_id = $order_item->getStatus();
                                if($status_id == 0)
                                    echo __("New");
                                if($status_id == 1)
                                    echo __("Ready To Receive");
                                if($status_id == 2)
                                    echo __("Received");   
                                if($status_id == 3)
                                    echo __("Canceled");      ?> 
                                </span></strong>
                            </td>
                        </tr>
                    </tbody>
<?php           $count++;
                }           ?>
                </table>
            </div>
        </div>
    </section>
    <section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="box-left admin__page-section-item order-comments-history">
            <div class="entry-edit">
                <div class="entry-edit-head admin__page-section-item-title">
                    <span class="title">Comments History</span>
                </div>
                <fieldset>
                     <div id="order_history_block">
                        <div class="order-history-form" id="history_form">
                            <div>Add Order Comments</div>
                            <div class="field-row admin__field">
                                <label class="normal admin__field-label">Status</label><br>
                                <div class="admin__field-control">
                                    <select class="select admin__control-select" name="status" id="picking_status">
    <?php                               if($status_id == 0)
                                            echo "<option value='0'>".__("New")."</option>";
                                        if($status_id == 1)
                                            echo "<option value='1'>".__("Ready To Receive")."</option>";
                                        if($status_id == 2)
                                            echo "<option value='2'>".__("Received")."</option>";  
                                        if($status_id == 3)
                                            echo "<option value='3'>".__("Canceled")."</option>";     ?>
                                    </select>
                                </div>
                            </div>
                            <div class="field-row admin__field">
                                <label class="normal admin__field-label">Comment</label>
                                <textarea id="main_comment" style="height:6em; width:99%;" cols="5" rows="3" name="comment"></textarea>
                            </div>
                            <div class="f-left admin__field">
                                <div class="order-history-comments-options">
                                    <input type="checkbox" value="1" id="comment_notify" name="is_customer_notified">
                                    <label class="normal" for="comment_notify"> Notify Supplier by Email</label>
                                </div>
                                <div class="f-right order-history-comments-actions">
                                    <button id="submit_comment" data-pickingid="<?php echo $this->getRequest()->getParam("id")?>" class="scalable save" type="button" title="Submit Comment"><span><span><span>Submit Comment</span></span></span></button>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="divider"></div>
                        <ul class="note-list">
<?php                       $picking_id = $this->getRequest()->getParam("id");
                            $collection = $block->getCommentObj($picking_id);
                            $collection->setOrder('entity_id','DESC');
                            foreach($collection as $one_comment) {        ?>
                            <li>
                                <strong>
<?php                               $date = date_create($one_comment->getCreatedAt());echo date_format($date, "g:ia \o\\n l jS F Y"); ?>
                                </strong>
                                <span class="separator">|</span>
                                <strong>
<?php                               $status_id = $one_comment->getStatus();
                                    if($status_id == 0)
                                        echo __("New");
                                    if($status_id == 1)
                                        echo __("Ready To Receive");
                                    if($status_id == 2)
                                        echo __("Received"); 
                                    if($status_id == 3)
                                        echo __("Canceled");?>
                                </strong><br>
                                <small>Supplier
<?php                               if($one_comment->getIsSupplierNotified() == 1)  {   ?>
                                        <strong class="subdue">Notified<img width="16" height="16" src="<?php echo $this->getSkinUrl("images/ico_success.gif");?>"></strong>
<?php                               }
                                    else   {   ?>
                                        <strong class="subdue">Not Notified</strong>
<?php                               }   ?>
                                </small><br>
<?php                           echo $one_comment->getComment();   ?>
                            </li>
<?php                       }           ?>
                        </ul>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    </section>
</div>
<div class="popup_background" id="popup_background">
    <form action="<?php echo $this->getUrl('*/*/receiveProducts', array('id' => $this->getRequest()->getParam('id'))); ?>" method="get" id="wk-partialshipment" enctype="multipart/form-data" novalidate="novalidate">
    <table cellspacing="0" class="data order-tables data-table admin__table-primary edit-order-table">
        <thead>
            <tr>
                <th>Product</th>
                <th class="a-center">Weight</th>
                <th class="a-center ">Receive Qty</th>
            </tr>
        </thead>
<?php   $count = 1;
        $collection = $block->getMoveObj()->getCollection()->addFieldToFilter("picking_id",$this->getRequest()->getParam("id"));
        foreach ($collection as $order_item) {          ?>
            <tbody class="<?php if($count % 2 == 0)echo 'even';else echo 'odd';?>">
                <tr class="border">
                    <td>
                        <div class="item-container">
                            <div class="item-text">
                                <h5 class="title">
                                    <span><?php echo $order_item->getDescription(); ?></span>
                                </h5>
                                <div><strong>SKU:</strong><?php echo $order_item->getSku(); ?></div>
<?php                                   $option_array = unserialize($order_item->getCustomOptions());
                                if($option_array && isset($option_array["options"])){  ?>
                                    <dl class="item-options">
                                    <?php foreach($option_array["options"] as $option) {  ?>
                                            <dt><?php echo $option["label"];?></dt>
                                            <dd><?php echo $option["value"];?></dd>
                                    <?php  }       ?>
                                    </dl>
<?php                           }   ?>
                            </div>
                        </div>
                    </td>
                    <td class="a-center"><strong><span><?php echo $order_item->getWeight();?></span></td>
                    <td>
                        <table cellspacing="0" class="qty-table">
                            <tbody>
                                <tr>
                                    <td><strong><input type="text" name="qty[<?php echo $order_item->getProductId(); ?>]" 
                                    class="a-center prod_qty admin__control-text required-entry _required validate-digits" value="<?php echo $order_item->getQuantity()-$order_item->getReceivedQty(); ?>"/></strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
<?php           $count++;
        }           ?>
        </table>
    </form>
</div>

<?php
$formData = [
    'comment_url' =>  $block->getUrl("purchasemanagement/history/save", ["_secure" => $this->getRequest()->isSecure()])
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "picking": <?php  echo $serializedFormData; ?>
        }
    }
</script>

